### ISSUE TITLE
ADP source

### ISSUE THREAD

**Issue by nitroshift** [MarvellEmbeddedProcessors/openwrt-marvell-swip#1]
The ADP SDK download link is missing. Any chance it can be uploaded here?

nitroshift

**Comment by timork** [comment]
ADP SDK provided via Marvell Extranet accounting system.
For evaluation purposes you can use WRT14.04 [binary image](https://github.com/MarvellEmbeddedProcessors/openwrt-marvell-swip/tree/binaries) with pre-integrated ADP.

**Comment by nitroshift** [comment]
I actually wanted to port ADP to other Armada SoC's too.

**Comment by nitroshift** [comment]
Since I understand that the package cannot be made public, could you please build a firmware image for the WRT1900AC v1, based on Armada XP? Thank you!
